version: 1.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
init:
- ps: ''
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: build/XboxRainDroplets.sln
  verbosity: minimal
before_package:
- cmd: release.bat
after_build:
- ps: Get-ChildItem .\bin\*.zip  | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }